import { DataTypes } from 'sequelize';
import { sequelize } from '../config/database.js';

/** Solo campos específicos de gestantes (Option A). Comunes en IngresoFamiliaMiembro. */
export const IngresoMiembroGestante = sequelize.define('IngresoMiembroGestante', {
  id: { type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true },
  miembro_ingreso_id: { type: DataTypes.BIGINT, allowNull: false, unique: true },
  cx_genitourinaria: { type: DataTypes.BOOLEAN },
  infertilidad: { type: DataTypes.BOOLEAN },
  cardiopatia: { type: DataTypes.BOOLEAN },
  nefropatia: { type: DataTypes.BOOLEAN },
  violencia: { type: DataTypes.BOOLEAN },
  tuberculosis: { type: DataTypes.BOOLEAN },
  diabetes: { type: DataTypes.BOOLEAN },
  hipertension: { type: DataTypes.BOOLEAN },
  preeclampsia: { type: DataTypes.BOOLEAN },
  eclampsia: { type: DataTypes.BOOLEAN },
  otra_cond_med_grave: { type: DataTypes.BOOLEAN },
  otra_cond_med_cual: { type: DataTypes.TEXT },
  gestaciones_previas: { type: DataTypes.INTEGER },
  abortos: { type: DataTypes.INTEGER },
  ectopicos: { type: DataTypes.INTEGER },
  partos_vaginales: { type: DataTypes.INTEGER },
  cesareas: { type: DataTypes.INTEGER },
  nacidos_muertos: { type: DataTypes.INTEGER },
  bajo_peso_nacer: { type: DataTypes.INTEGER },
  macrosomia: { type: DataTypes.INTEGER },
  gemelares: { type: DataTypes.INTEGER },
  muertos_primera_sem: { type: DataTypes.INTEGER },
  muertos_despues_primera_sem: { type: DataTypes.INTEGER },
  fecha_fin_ultima_gestacion: { type: DataTypes.DATEONLY },
  embarazo_planeado: { type: DataTypes.BOOLEAN },
  planificaba: { type: DataTypes.BOOLEAN },
  falla_metodo: { type: DataTypes.BOOLEAN },
  metodo_planificacion: { type: DataTypes.TEXT },
  fum: { type: DataTypes.DATEONLY },
  fum_confiable: { type: DataTypes.BOOLEAN },
  eco_menor_20s: { type: DataTypes.BOOLEAN },
  fpp: { type: DataTypes.DATEONLY },
  edad_gestacional_semanas: { type: DataTypes.INTEGER },
  edad_gestacional_dias: { type: DataTypes.INTEGER },
  fumadora_activa: { type: DataTypes.BOOLEAN },
  fumadora_pasiva: { type: DataTypes.BOOLEAN },
  consume_alcohol: { type: DataTypes.BOOLEAN },
  consume_drogas: { type: DataTypes.BOOLEAN },
  violencia_actual: { type: DataTypes.BOOLEAN },
  controles_prenatales: { type: DataTypes.BOOLEAN },
  trimestre_ingreso: { type: DataTypes.INTEGER },
  num_controles_prenatales: { type: DataTypes.INTEGER },
  riesgo: { type: DataTypes.TEXT },
  vacuna_antirrubeola_completa: { type: DataTypes.BOOLEAN },
  vacuna_antitetanica_completa: { type: DataTypes.BOOLEAN },
  odonto_realizado: { type: DataTypes.BOOLEAN },
  odonto_resultado: { type: DataTypes.TEXT },
  mamas_realizado: { type: DataTypes.BOOLEAN },
  mamas_resultado: { type: DataTypes.TEXT },
  citologia_realizado: { type: DataTypes.BOOLEAN },
  citologia_resultado: { type: DataTypes.TEXT },
  hemoclasificacion_realizado: { type: DataTypes.BOOLEAN },
  hemoclasificacion_resultado: { type: DataTypes.TEXT },
  hemoglobina_realizado: { type: DataTypes.BOOLEAN },
  hemoglobina_resultado: { type: DataTypes.TEXT },
  glicemia_realizado: { type: DataTypes.BOOLEAN },
  glicemia_resultado: { type: DataTypes.TEXT },
  uroanalisis_realizado: { type: DataTypes.BOOLEAN },
  uroanalisis_resultado: { type: DataTypes.TEXT },
  vdrl_realizado: { type: DataTypes.BOOLEAN },
  vdrl_resultado: { type: DataTypes.TEXT },
  vdrl_2_muestra_realizado: { type: DataTypes.BOOLEAN },
  vdrl_2_muestra_resultado: { type: DataTypes.TEXT },
  vih_realizado: { type: DataTypes.BOOLEAN },
  vih_resultado: { type: DataTypes.TEXT },
  hepatitis_b_realizado: { type: DataTypes.BOOLEAN },
  hepatitis_b_resultado: { type: DataTypes.TEXT },
  toxoplasmosis_realizado: { type: DataTypes.BOOLEAN },
  toxoplasmosis_resultado: { type: DataTypes.TEXT },
  malaria_realizado: { type: DataTypes.BOOLEAN },
  malaria_resultado: { type: DataTypes.TEXT },
  chagas_realizado: { type: DataTypes.BOOLEAN },
  chagas_resultado: { type: DataTypes.TEXT },
  cultivo_egb_realizado: { type: DataTypes.BOOLEAN },
  cultivo_egb_resultado: { type: DataTypes.TEXT },
  ecografia_realizado: { type: DataTypes.BOOLEAN },
  ecografia_resultado: { type: DataTypes.TEXT },
  grupo: { type: DataTypes.TEXT },
  rh: { type: DataTypes.TEXT },
  acido_folico: { type: DataTypes.BOOLEAN },
  calcio: { type: DataTypes.BOOLEAN },
  sulfato_ferroso: { type: DataTypes.BOOLEAN },
  consejeria_lactancia: { type: DataTypes.BOOLEAN },
  preparacion_parto: { type: DataTypes.BOOLEAN },
  peso_kg: { type: DataTypes.DECIMAL },
  estatura_cm: { type: DataTypes.DECIMAL },
  pa_sistolica: { type: DataTypes.INTEGER },
  pa_diastolica: { type: DataTypes.INTEGER },
  movimientos_fetales: { type: DataTypes.BOOLEAN },
  morbilidad_sentida: { type: DataTypes.BOOLEAN },
  morbilidad_sentida_describe: { type: DataTypes.TEXT },
  observaciones_adicionales: { type: DataTypes.TEXT },
}, {
  tableName: 'ingreso_miembro_gestante',
  timestamps: true,
  createdAt: 'creado_en',
  updatedAt: false,
  underscored: true,
});
