import { DataTypes } from 'sequelize';
import { sequelize } from '../config/database.js';

export const IngresoFamiliaMiembro = sequelize.define('IngresoFamiliaMiembro', {
  id: { type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true },
  ingreso_id: { type: DataTypes.BIGINT, allowNull: false },
  fecha_apertura: { type: DataTypes.DATEONLY },
  vivienda_numero: { type: DataTypes.TEXT },
  numero_familia: { type: DataTypes.TEXT },
  apellidos_familia: { type: DataTypes.TEXT },
  num_en_familia: { type: DataTypes.INTEGER },
  doc_tipo: { type: DataTypes.TEXT },
  doc_numero: { type: DataTypes.TEXT },
  nombres: { type: DataTypes.TEXT },
  apellidos: { type: DataTypes.TEXT },
  parentesco: { type: DataTypes.TEXT },
  fecha_nacimiento: { type: DataTypes.DATEONLY },
  edad_anios: { type: DataTypes.INTEGER },
  edad_meses: { type: DataTypes.INTEGER },
  edad_dias: { type: DataTypes.INTEGER },
  sexo: { type: DataTypes.TEXT },
  poblacion: { type: DataTypes.TEXT },
  estado_civil: { type: DataTypes.TEXT },
  actualmente_estudiando: { type: DataTypes.BOOLEAN },
  estado_escolaridad: { type: DataTypes.TEXT },
  ultimo_anio_aprobado: { type: DataTypes.TEXT },
  posicion_ocupacional: { type: DataTypes.TEXT },
  /* Campos comunes movidos desde tablas por edad (Option A) */
  etnia: { type: DataTypes.TEXT },
  doc_otro: { type: DataTypes.TEXT },
  poblacion_prioritaria_1: { type: DataTypes.TEXT },
  poblacion_prioritaria_2: { type: DataTypes.TEXT },
  hecho_victimizante: { type: DataTypes.TEXT },
  declaracion_desplazamiento: { type: DataTypes.BOOLEAN },
  tipo_discapacidad: { type: DataTypes.TEXT },
  en_programa_discapacidad: { type: DataTypes.BOOLEAN },
  familias_en_accion: { type: DataTypes.BOOLEAN },
  mana: { type: DataTypes.BOOLEAN },
  red_unidos: { type: DataTypes.BOOLEAN },
  desmovilizado: { type: DataTypes.BOOLEAN },
  adulto_mayor: { type: DataTypes.BOOLEAN },
  otro_programa: { type: DataTypes.BOOLEAN },
  otro_programa_cual: { type: DataTypes.TEXT },
  encuestado: { type: DataTypes.BOOLEAN },
  listado_censal: { type: DataTypes.BOOLEAN },
  sisben_puntaje: { type: DataTypes.DECIMAL },
  sisben_municipio: { type: DataTypes.TEXT },
  tipo_afiliacion: { type: DataTypes.TEXT },
  eps_nombre: { type: DataTypes.TEXT },
  eps_cual: { type: DataTypes.TEXT },
  eps_municipio: { type: DataTypes.TEXT },
  analfabetismo: { type: DataTypes.BOOLEAN },
  morbilidad_cronica: { type: DataTypes.TEXT },
  morbilidad_cronica_otro: { type: DataTypes.TEXT },
  consulta_programa_ultimo_anio: { type: DataTypes.BOOLEAN },
  consulta_medica_ult_6m: { type: DataTypes.BOOLEAN },
  motivo_consulta: { type: DataTypes.TEXT },
  peso_kg: { type: DataTypes.DECIMAL },
  estatura_cm: { type: DataTypes.DECIMAL },
  signos_desnutricion: { type: DataTypes.BOOLEAN },
  sobrepeso_observacion: { type: DataTypes.BOOLEAN },
  imc: { type: DataTypes.DECIMAL },
  clasificacion_nutricional: { type: DataTypes.TEXT },
  planificacion_familiar: { type: DataTypes.BOOLEAN },
  metodo_planificacion: { type: DataTypes.TEXT },
  atencion_preventiva_odontologica: { type: DataTypes.BOOLEAN },
  agudeza_visual: { type: DataTypes.BOOLEAN },
  cintura_cm_hombre: { type: DataTypes.DECIMAL },
  cintura_cm_mujer: { type: DataTypes.DECIMAL },
  cadera_cm_hombre: { type: DataTypes.DECIMAL },
  cadera_cm_mujer: { type: DataTypes.DECIMAL },
  relacion_icc_hombre: { type: DataTypes.DECIMAL },
  relacion_icc_mujer: { type: DataTypes.DECIMAL },
  pa_sistolica_hombre: { type: DataTypes.INTEGER },
  pa_sistolica_mujer: { type: DataTypes.INTEGER },
  pa_diastolica_hombre: { type: DataTypes.INTEGER },
  pa_diastolica_mujer: { type: DataTypes.INTEGER },
  autoexamen_mama_testiculo: { type: DataTypes.BOOLEAN },
  vacunacion_cumple_esquema: { type: DataTypes.BOOLEAN },
  citologia_alguna_vez: { type: DataTypes.BOOLEAN },
  citologia_anio_ultima: { type: DataTypes.INTEGER },
  citologia_resultado: { type: DataTypes.TEXT },
  mamografia_cada2_anios: { type: DataTypes.BOOLEAN },
  mamografia_anio_ultima: { type: DataTypes.INTEGER },
  mamografia_resultado: { type: DataTypes.TEXT },
  examen_prostata_anual: { type: DataTypes.BOOLEAN },
  examen_prostata_resultado: { type: DataTypes.TEXT },
  fuma: { type: DataTypes.BOOLEAN },
  anios_fumador: { type: DataTypes.INTEGER },
  cigarrillos_por_dia: { type: DataTypes.INTEGER },
  morbilidad_sentida: { type: DataTypes.BOOLEAN },
  morbilidad_sentida_describe: { type: DataTypes.TEXT },
  diagnostico_cie10: { type: DataTypes.TEXT },
  observaciones_adicionales: { type: DataTypes.TEXT },
}, {
  tableName: 'ingreso_familia_miembro',
  timestamps: true,
  createdAt: 'creado_en',
  updatedAt: false,
  underscored: true,
});
