import { DataTypes } from 'sequelize';
import { sequelize } from '../config/database.js';

export const IngresoVivienda = sequelize.define('IngresoVivienda', {
  id: { type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true },
  ingreso_id: { type: DataTypes.BIGINT, allowNull: false },
  periodo_academico: { type: DataTypes.TEXT },
  fecha_apertura: { type: DataTypes.DATEONLY },
  nombre_encuestador: { type: DataTypes.TEXT },
  vivienda_numero: { type: DataTypes.TEXT },
  num_familias_en_vivienda: { type: DataTypes.INTEGER },
  municipio: { type: DataTypes.TEXT },
  corregimiento: { type: DataTypes.TEXT },
  vereda: { type: DataTypes.TEXT },
  barrio: { type: DataTypes.TEXT },
  zona_ubicacion: { type: DataTypes.TEXT },
  direccion: { type: DataTypes.TEXT },
  telefono: { type: DataTypes.TEXT },
  distancia_minutos_cabecera: { type: DataTypes.INTEGER },
  medio_transporte: { type: DataTypes.TEXT },
  tipo_vivienda: { type: DataTypes.TEXT },
  estado_vivienda: { type: DataTypes.TEXT },
  vivienda_es: { type: DataTypes.TEXT },
  vivienda_es_otro: { type: DataTypes.TEXT },
  uso_vivienda: { type: DataTypes.TEXT },
  uso_vivienda_otro: { type: DataTypes.TEXT },
  tipo_alumbrado: { type: DataTypes.TEXT },
  pisos: { type: DataTypes.TEXT },
  pisos_otro: { type: DataTypes.TEXT },
  paredes: { type: DataTypes.TEXT },
  paredes_otro: { type: DataTypes.TEXT },
  techo: { type: DataTypes.TEXT },
  techo_otro: { type: DataTypes.TEXT },
  dispositivos_electricos: { type: DataTypes.TEXT },
  electricos_aislados: { type: DataTypes.BOOLEAN },
  electricos_riesgo: { type: DataTypes.BOOLEAN },
  tipo_fuente_agua: { type: DataTypes.TEXT },
  fuente_superficial: { type: DataTypes.TEXT },
  estado_fuente: { type: DataTypes.TEXT },
  conexion_acueducto: { type: DataTypes.TEXT },
  calidad_agua: { type: DataTypes.TEXT },
  tratamiento_agua: { type: DataTypes.TEXT },
  artefacto_excretas: { type: DataTypes.TEXT },
  artefacto_excretas_otro: { type: DataTypes.TEXT },
  disposicion_excretas: { type: DataTypes.TEXT },
  disposicion_excretas_otro: { type: DataTypes.TEXT },
  disposicion_aguas_grises: { type: DataTypes.TEXT },
  disposicion_aguas_grises_otro: { type: DataTypes.TEXT },
  artefacto_basuras: { type: DataTypes.TEXT },
  artefacto_basuras_otro: { type: DataTypes.TEXT },
  recoleccion_vivienda: { type: DataTypes.TEXT },
  realiza_separacion: { type: DataTypes.BOOLEAN },
  realiza_tratamiento: { type: DataTypes.TEXT },
  disposicion_final_basuras: { type: DataTypes.TEXT },
  hacinamiento: { type: DataTypes.BOOLEAN },
  num_cuartos: { type: DataTypes.INTEGER },
  buen_estado_higienico: { type: DataTypes.BOOLEAN },
  roedores_insectos: { type: DataTypes.BOOLEAN },
  iluminacion_adecuada: { type: DataTypes.BOOLEAN },
  ventilacion_adecuada: { type: DataTypes.BOOLEAN },
  espacios_convivencia: { type: DataTypes.BOOLEAN },
  diseno_estructuras_adecuadas: { type: DataTypes.BOOLEAN },
  servicios_basicos_buena_calidad: { type: DataTypes.BOOLEAN },
  terreno_estable: { type: DataTypes.BOOLEAN },
  cocina_dispone: { type: DataTypes.BOOLEAN },
  cocina_independiente: { type: DataTypes.BOOLEAN },
  cocina_buenas_condiciones: { type: DataTypes.BOOLEAN },
  fogon_gas: { type: DataTypes.BOOLEAN },
  fogon_electrico: { type: DataTypes.BOOLEAN },
  fogon_abierto_combustible: { type: DataTypes.BOOLEAN },
  tiene_animales: { type: DataTypes.BOOLEAN },
}, {
  tableName: 'ingreso_vivienda',
  timestamps: true,
  createdAt: 'creado_en',
  updatedAt: false,
  underscored: true,
});
