CREATE TABLE IF NOT EXISTS ingreso_vivienda (
  id BIGSERIAL PRIMARY KEY,
  ingreso_id BIGINT NOT NULL REFERENCES ingreso_familia(id) ON DELETE CASCADE,
  periodo_academico TEXT,
  fecha_apertura DATE,
  nombre_encuestador TEXT,
  vivienda_numero TEXT,
  num_familias_en_vivienda INT,
  municipio TEXT,
  corregimiento TEXT,
  vereda TEXT,
  barrio TEXT,
  zona_ubicacion TEXT,
  direccion TEXT,
  telefono TEXT,
  distancia_minutos_cabecera INT,
  medio_transporte TEXT,
  tipo_vivienda TEXT,
  estado_vivienda TEXT,
  vivienda_es TEXT,
  vivienda_es_otro TEXT,
  uso_vivienda TEXT,
  uso_vivienda_otro TEXT,
  tipo_alumbrado TEXT,
  pisos TEXT,
  pisos_otro TEXT,
  paredes TEXT,
  paredes_otro TEXT,
  techo TEXT,
  techo_otro TEXT,
  dispositivos_electricos TEXT,
  electricos_aislados BOOLEAN,
  electricos_riesgo BOOLEAN,
  tipo_fuente_agua TEXT,
  fuente_superficial TEXT,
  estado_fuente TEXT,
  conexion_acueducto TEXT,
  calidad_agua TEXT,
  tratamiento_agua TEXT,
  artefacto_excretas TEXT,
  artefacto_excretas_otro TEXT,
  disposicion_excretas TEXT,
  disposicion_excretas_otro TEXT,
  disposicion_aguas_grises TEXT,
  disposicion_aguas_grises_otro TEXT,
  artefacto_basuras TEXT,
  artefacto_basuras_otro TEXT,
  recoleccion_vivienda TEXT,
  realiza_separacion BOOLEAN,
  realiza_tratamiento TEXT,
  disposicion_final_basuras TEXT,
  hacinamiento BOOLEAN,
  num_cuartos INT,
  buen_estado_higienico BOOLEAN,
  roedores_insectos BOOLEAN,
  iluminacion_adecuada BOOLEAN,
  ventilacion_adecuada BOOLEAN,
  espacios_convivencia BOOLEAN,
  diseno_estructuras_adecuadas BOOLEAN,
  servicios_basicos_buena_calidad BOOLEAN,
  terreno_estable BOOLEAN,
  cocina_dispone BOOLEAN,
  cocina_independiente BOOLEAN,
  cocina_buenas_condiciones BOOLEAN,
  fogon_gas BOOLEAN,
  fogon_electrico BOOLEAN,
  fogon_abierto_combustible BOOLEAN,
  tiene_animales BOOLEAN,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ingreso_vivienda_animal (
  id BIGSERIAL PRIMARY KEY,
  ingreso_vivienda_id BIGINT NOT NULL REFERENCES ingreso_vivienda(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL,
  descripcion_otro TEXT,
  tiene BOOLEAN,
  cantidad INT,
  vacunados INT,
  esterilizados INT,
  desparasitados INT,
  creado_en TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(ingreso_vivienda_id, tipo)
);

CREATE INDEX IF NOT EXISTS idx_ingreso_vivienda_ingreso ON ingreso_vivienda(ingreso_id);
CREATE INDEX IF NOT EXISTS idx_ingreso_vivienda_animal_vivienda ON ingreso_vivienda_animal(ingreso_vivienda_id);
