-- Option A: todos los campos comunes en ingreso_familia_miembro
CREATE TABLE IF NOT EXISTS ingreso_familia_miembro (
  id BIGSERIAL PRIMARY KEY,
  ingreso_id BIGINT NOT NULL REFERENCES ingreso_familia(id) ON DELETE CASCADE,
  fecha_apertura DATE,
  vivienda_numero TEXT,
  numero_familia TEXT,
  apellidos_familia TEXT,
  num_en_familia INT,
  doc_tipo TEXT,
  doc_numero TEXT,
  nombres TEXT,
  apellidos TEXT,
  parentesco TEXT,
  fecha_nacimiento DATE,
  edad_anios INT,
  edad_meses INT,
  edad_dias INT,
  sexo TEXT,
  poblacion TEXT,
  estado_civil TEXT,
  actualmente_estudiando BOOLEAN,
  estado_escolaridad TEXT,
  ultimo_anio_aprobado TEXT,
  posicion_ocupacional TEXT,
  etnia TEXT,
  doc_otro TEXT,
  poblacion_prioritaria_1 TEXT,
  poblacion_prioritaria_2 TEXT,
  hecho_victimizante TEXT,
  declaracion_desplazamiento BOOLEAN,
  tipo_discapacidad TEXT,
  en_programa_discapacidad BOOLEAN,
  familias_en_accion BOOLEAN,
  mana BOOLEAN,
  red_unidos BOOLEAN,
  desmovilizado BOOLEAN,
  adulto_mayor BOOLEAN,
  otro_programa BOOLEAN,
  otro_programa_cual TEXT,
  encuestado BOOLEAN,
  listado_censal BOOLEAN,
  sisben_puntaje NUMERIC,
  sisben_municipio TEXT,
  tipo_afiliacion TEXT,
  eps_nombre TEXT,
  eps_cual TEXT,
  eps_municipio TEXT,
  analfabetismo BOOLEAN,
  morbilidad_cronica TEXT,
  morbilidad_cronica_otro TEXT,
  consulta_programa_ultimo_anio BOOLEAN,
  consulta_medica_ult_6m BOOLEAN,
  motivo_consulta TEXT,
  peso_kg NUMERIC,
  estatura_cm NUMERIC,
  signos_desnutricion BOOLEAN,
  sobrepeso_observacion BOOLEAN,
  imc NUMERIC,
  clasificacion_nutricional TEXT,
  planificacion_familiar BOOLEAN,
  metodo_planificacion TEXT,
  atencion_preventiva_odontologica BOOLEAN,
  agudeza_visual BOOLEAN,
  cintura_cm_hombre NUMERIC,
  cintura_cm_mujer NUMERIC,
  cadera_cm_hombre NUMERIC,
  cadera_cm_mujer NUMERIC,
  relacion_icc_hombre NUMERIC,
  relacion_icc_mujer NUMERIC,
  pa_sistolica_hombre INT,
  pa_sistolica_mujer INT,
  pa_diastolica_hombre INT,
  pa_diastolica_mujer INT,
  autoexamen_mama_testiculo BOOLEAN,
  vacunacion_cumple_esquema BOOLEAN,
  citologia_alguna_vez BOOLEAN,
  citologia_anio_ultima INT,
  citologia_resultado TEXT,
  mamografia_cada2_anios BOOLEAN,
  mamografia_anio_ultima INT,
  mamografia_resultado TEXT,
  examen_prostata_anual BOOLEAN,
  examen_prostata_resultado TEXT,
  fuma BOOLEAN,
  anios_fumador INT,
  cigarrillos_por_dia INT,
  morbilidad_sentida BOOLEAN,
  morbilidad_sentida_describe TEXT,
  diagnostico_cie10 TEXT,
  observaciones_adicionales TEXT,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ingreso_fam_miembro_ingreso_num ON ingreso_familia_miembro(ingreso_id, num_en_familia);
CREATE INDEX IF NOT EXISTS idx_ingreso_fam_miembro_ingreso ON ingreso_familia_miembro(ingreso_id);
