-- Tablas por rango de edad / gestantes (Option A: solo campos específicos)

CREATE TABLE IF NOT EXISTS ingreso_miembro_0a18 (
  id BIGSERIAL PRIMARY KEY,
  miembro_ingreso_id BIGINT NOT NULL UNIQUE REFERENCES ingreso_familia_miembro(id) ON DELETE CASCADE,
  lm_exclusiva BOOLEAN,
  lm_exclusiva_meses INT,
  progr_crec_desarrollo BOOLEAN,
  eda_en_semestre BOOLEAN,
  eda_num_episodios INT,
  eda_sabe_manejo BOOLEAN,
  ira_en_semestre BOOLEAN,
  ira_num_episodios INT,
  ira_sabe_manejo BOOLEAN,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ingreso_miembro_19a44 (
  id BIGSERIAL PRIMARY KEY,
  miembro_ingreso_id BIGINT NOT NULL UNIQUE REFERENCES ingreso_familia_miembro(id) ON DELETE CASCADE,
  observaciones_adicionales TEXT,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ingreso_miembro_45mas (
  id BIGSERIAL PRIMARY KEY,
  miembro_ingreso_id BIGINT NOT NULL UNIQUE REFERENCES ingreso_familia_miembro(id) ON DELETE CASCADE,
  observaciones_adicionales TEXT,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ingreso_miembro_gestante (
  id BIGSERIAL PRIMARY KEY,
  miembro_ingreso_id BIGINT NOT NULL UNIQUE REFERENCES ingreso_familia_miembro(id) ON DELETE CASCADE,
  cx_genitourinaria BOOLEAN,
  infertilidad BOOLEAN,
  cardiopatia BOOLEAN,
  nefropatia BOOLEAN,
  violencia BOOLEAN,
  tuberculosis BOOLEAN,
  diabetes BOOLEAN,
  hipertension BOOLEAN,
  preeclampsia BOOLEAN,
  eclampsia BOOLEAN,
  otra_cond_med_grave BOOLEAN,
  otra_cond_med_cual TEXT,
  gestaciones_previas INT,
  abortos INT,
  ectopicos INT,
  partos_vaginales INT,
  cesareas INT,
  nacidos_muertos INT,
  bajo_peso_nacer INT,
  macrosomia INT,
  gemelares INT,
  muertos_primera_sem INT,
  muertos_despues_primera_sem INT,
  fecha_fin_ultima_gestacion DATE,
  embarazo_planeado BOOLEAN,
  planificaba BOOLEAN,
  falla_metodo BOOLEAN,
  metodo_planificacion TEXT,
  fum DATE,
  fum_confiable BOOLEAN,
  eco_menor_20s BOOLEAN,
  fpp DATE,
  edad_gestacional_semanas INT,
  edad_gestacional_dias INT,
  fumadora_activa BOOLEAN,
  fumadora_pasiva BOOLEAN,
  consume_alcohol BOOLEAN,
  consume_drogas BOOLEAN,
  violencia_actual BOOLEAN,
  controles_prenatales BOOLEAN,
  trimestre_ingreso INT,
  num_controles_prenatales INT,
  riesgo TEXT,
  vacuna_antirrubeola_completa BOOLEAN,
  vacuna_antitetanica_completa BOOLEAN,
  odonto_realizado BOOLEAN,
  odonto_resultado TEXT,
  mamas_realizado BOOLEAN,
  mamas_resultado TEXT,
  citologia_realizado BOOLEAN,
  citologia_resultado TEXT,
  hemoclasificacion_realizado BOOLEAN,
  hemoclasificacion_resultado TEXT,
  hemoglobina_realizado BOOLEAN,
  hemoglobina_resultado TEXT,
  glicemia_realizado BOOLEAN,
  glicemia_resultado TEXT,
  uroanalisis_realizado BOOLEAN,
  uroanalisis_resultado TEXT,
  vdrl_realizado BOOLEAN,
  vdrl_resultado TEXT,
  vdrl_2_muestra_realizado BOOLEAN,
  vdrl_2_muestra_resultado TEXT,
  vih_realizado BOOLEAN,
  vih_resultado TEXT,
  hepatitis_b_realizado BOOLEAN,
  hepatitis_b_resultado TEXT,
  toxoplasmosis_realizado BOOLEAN,
  toxoplasmosis_resultado TEXT,
  malaria_realizado BOOLEAN,
  malaria_resultado TEXT,
  chagas_realizado BOOLEAN,
  chagas_resultado TEXT,
  cultivo_egb_realizado BOOLEAN,
  cultivo_egb_resultado TEXT,
  ecografia_realizado BOOLEAN,
  ecografia_resultado TEXT,
  grupo TEXT,
  rh TEXT,
  acido_folico BOOLEAN,
  calcio BOOLEAN,
  sulfato_ferroso BOOLEAN,
  consejeria_lactancia BOOLEAN,
  preparacion_parto BOOLEAN,
  peso_kg NUMERIC,
  estatura_cm NUMERIC,
  pa_sistolica INT,
  pa_diastolica INT,
  movimientos_fetales BOOLEAN,
  morbilidad_sentida BOOLEAN,
  morbilidad_sentida_describe TEXT,
  observaciones_adicionales TEXT,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ingreso_miembro_0a18_miembro ON ingreso_miembro_0a18(miembro_ingreso_id);
CREATE INDEX IF NOT EXISTS idx_ingreso_miembro_19a44_miembro ON ingreso_miembro_19a44(miembro_ingreso_id);
CREATE INDEX IF NOT EXISTS idx_ingreso_miembro_45mas_miembro ON ingreso_miembro_45mas(miembro_ingreso_id);
CREATE INDEX IF NOT EXISTS idx_ingreso_miembro_gestante_miembro ON ingreso_miembro_gestante(miembro_ingreso_id);
